name: iron_beam
description: "IronBeam: Machine interpretable Notion and Manager of Construction Blueprint for to produce Infrastructural software system."
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  apollovm: ^0.0.31
  c: any
  tokens: any
#   path: ^1.8.0
dependency_overrides:
  c:
    path: "D:\\Users\\haruka.dev\\ResDev\\_Codes\\Lang\\Dart\\.CoreLibraries\\c"
  tokens:
    path: "D:\\Users\\haruka.dev\\ResDev\\_Codes\\Lang\\Dart\\.CoreLibraries\\Tokens"
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
